---
- hosts: all
  become: true
  vars:
    password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters') }}"
  tasks:
    - name: install aptitude with apt
      apt: name=aptitude update_cache=yes force_apt_get=yes
    - name: Install required system packages
      apt: name={{ item }} update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'git', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
    - name: Add docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Install docker-compose
      pip:
        name: docker-compose
    - name: Allow user to use docker without sudo
      user:
        name: odoo
        groups: docker
        append: yes
    - name: Clone repo
      become: yes
      become_user: odoo
      git:
        repo: "https://github.com/alabs/rj-odoo"
        version: master
        dest: /home/odoo/odoo
    - name: Fill odoo credentials
      template:
        src: templates/odoo.env.j2
        dest: /home/odoo/odoo/.odoo.env
        owner: odoo
        group: odoo
        mode: 0640
    - name: Fill db credentials
      template:
        src: templates/db.env.j2
        dest: /home/odoo/odoo/.db.env
        owner: odoo
        group: odoo
        mode: 0640
    - name: Run docker compose up
      become: yes
      become_user: odoo
      docker_compose:
        project_src: /home/odoo/odoo
